### PR TITLE
Issue 702 More informative error message for dependencies when deleting a network

### PR DESCRIPTION
**Pull request by mgulimonov**
Ref https://github.com/TheWeatherCompany/grid-api/issues/702

### CODE REVIEW

**Comment by ckelner** [comment]
@clstokes If you have time please.

**Comment by ckelner** [comment]
Please see comment https://github.com/TheWeatherCompany/dasein-cloud-aws/pull/100#issuecomment-44873864 regarding filtering.  We use filters from Grid today via this pattern.  Please take a look and let us know if we can leverage it instead.

**Comment by ckelner** [comment]
Ref: https://github.com/TheWeatherCompany/dasein-cloud-aws/pull/100

**Comment by mgulimonov** [comment]
Hey, @ckelner 
Could you please take another look at this PR?

**Pull request merged**
