### PR TITLE
Fix for task #152.

### PR DESCRIPTION
**Pull request by asmelkov**
closes https://github.com/TheWeatherCompany/grid-api/issues/152

### CODE REVIEW

**Comment by clstokes** [comment]
@asmelkov I'd rather do this differently, more like how it should have been done originally.

Please deprecate `setSubnetIds(..)` and `getSubnetIds()` in favor of `getSubnets()` and `setSubnets()` and store the real values in `String[] subnets` and convert `String subnets` to and from a string array in  `setSubnetIds(..)` and `getSubnetIds()`. Make sense?

**Comment by clstokes** [comment]
@asmelkov is this ready to go?

**Comment by asmelkov** [comment]
Hello Cameron, 
yes, everything is ready.

**Comment by clstokes** [comment]
:thumbsup:

**Comment by ckelner** [comment]
Testing.

**Pull request merged**
