### PR TITLE
add method for getting signed url for s3 bucket object

### PR DESCRIPTION
**Pull request by ckelner**
ref TheWeatherCompany/grid-api#374

### CODE REVIEW

**Comment by ckelner** [comment]
@clstokes please review

**Comment by clstokes** [comment]
Should the keys be pulled from the ProviderContext that's passed when BlobSupport is created, rather than passed in as parameters?

**Comment by ckelner** [comment]
Well in this case I believe we have different keys on our s3 bucket than what is being used for the IAM context.  See: https://github.com/TheWeatherCompany/grid-api/blob/master/grid-api-server/src/main/groovy/com/weather/grid/context/compute/CreateInstanceContextProvider.groovy#L103-L104 where we call to GridConfiguration for the bucket access keys specifically.

**Comment by ckelner** [comment]
@clstokes Do'h! Never merged!

**Pull request merged**
